### ISSUE TITLE
Restructure config to be one file (constants)

### ISSUE THREAD

**Issue by ckohen** [ckohen/corncierge#16]
config is a bit messy, most of the config will be constant anyways, including those pulled from .env
- [x] combine all files into constants
- [x] provide a way to change options via ApplicationOptions
- [x] validate options that aren't validated by deps
- [x] restructure application options in validation to be useable in application
- [x] change currently passed options to new ApplicationOptions structure
- [x] change to new options where necessary
- [x] document these changes
